### ISSUE TITLE
Infografia_DiegoAlexis

### ISSUE THREAD

**Issue by IrvingFernand0** [SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-DiegoSCP117#2]

**Comment by DiegoSCP117** [comment]
[Infografía - Diego Alexis Carlos Cruz.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-DiegoSCP117/files/12516444/Infografia.-.Diego.Alexis.Carlos.Cruz.pdf)

**Comment by abicoronel** [comment]
calificación: 20%

**Comment by josealfredo79** [comment]
Bien hehco y revisado..
